@HotelListing.API_HostAddress = http://localhost:5100


###

@countryId=3
GET {{HotelListing.API_HostAddress}}/api/countries

###

POST {{HotelListing.API_HostAddress}}/api/countries
Content-Type: application/json

{
  "Name" : "Test Country",
  "ShortName" : "TC"
}

###

DELETE {{HotelListing.API_HostAddress}}/api/countries/{{countryId}}

###

GET {{HotelListing.API_HostAddress}}/api/countries/{{countryId}}

###

PUT {{HotelListing.API_HostAddress}}/api/countries/{{countryId}}
Content-Type: application/json

{ 
  "CountryId": 3,
  "Name" : "Jamaica",
  "ShortName" : "JM"
}

###
@hotelId=5
GET {{HotelListing.API_HostAddress}}/api/hotels

###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Name" : "Test Hotel",
  "Adress" : "123 Main St",
  "Rating" : 4.5,
  "CountryId" : 3
}

###
DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}

###

GET {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}

###

PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}
Content-Type: application/json

{
  "Id" : 1,
  "Name" : "Ocean Hotel",
  "Adress" : "Errachidia, Morocco",
  "Rating" : 4,
  "CountryId" : 1
}


###
